# --- DEVELOPMENT (Windows) PORT & AYARLAR ---
server.port=8082

# --- WINDOWS (Development) MEDYA DOSYA YOLLARI ---
media.source.movies.path=D:\\SourceFiles\\mssql\\media\\videos\\movies
media.source.soap_operas.path=D:\\SourceFiles\\mssql\\media\\videos\\soap-operas
media.source.trailers.path=D:\\SourceFiles\\mssql\\media\\videos\\trailers
media.source.upcoming.path=D:\\SourceFiles\\mssql\\media\\videos\\upcoming
media.source.ads.path=D:\\SourceFiles\\mssql\\media\\videos\\ads
media.static.images.path=D:\\SourceFiles\\mssql\\media\\images\\static
media.profile.images.path=D:\\SourceFiles\\mssql\\media\\images\\profile
media.actor.images.path=D:\\SourceFiles\\mssql\\media\\images\\actors

# --- VERİTABANI BAĞLANTISI (DEV - SQL Server) ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=WhoDatIdols;encrypt=true;trustServerCertificate=true;integratedSecurity=false
spring.datasource.username=user
spring.datasource.password=sh218106
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
