# --- PRODUCTION (Linux) PORT & AYARLAR ---
server.port=8082

# --- LINUX (Production) MEDYA DOSYA YOLLARI ---
media.source.movies.path=/home/who-dat-idols/media/videos/movies
media.source.soap_operas.path=/home/who-dat-idols/media/videos/soap-operas
media.source.trailers.path=/home/who-dat-idols/media/videos/trailers
media.source.upcoming.path=/home/who-dat-idols/media/videos/upcoming
media.source.ads.path=/home/who-dat-idols/media/videos/ads
media.static.images.path=/home/who-dat-idols/media/images/static
media.profile.images.path=/home/who-dat-idols/media/images/profile
media.actor.images.path=/home/who-dat-idols/media/images/actors

# --- VERİTABANI BAĞLANTISI (PROD - Ortak WhoDatIdols DB) ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=WhoDatIdols;encrypt=true;trustServerCertificate=true;integratedSecurity=false
spring.datasource.username=sa
spring.datasource.password=Sh218106.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- PROXY VE REAL-IP AYARLARI ---
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
